name: Spencer Spezzano
markdown: redcarpet

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: From 123 To 012
description: Spencer Spezzano blog
author:
  name: Spencer Spezzano
  email: smspezzano@gmail.com
  github: https://github.com/smspezzano
  twitter: https://twitter.com/SpencerKFNP
  linkedin: https://www.linkedin.com/in/spencerspezzano
  bio: One man's journey into the world of programming!
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: 

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://spencerspezzano.com/myblog)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://smspezzano.github.io/myblog)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"

